# Generated by Django 4.2.5 on 2023-10-05 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('namscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
